modLoader="javafml"
loaderVersion="[4,)"
license="All-Rights-Reserved"

[[mods]]
modId="glass"
version="${version}"
displayName="GLASS Remastered"
description="General Laymans Aesthetic Spying Screen Remaster for Minecraft 1.21.1"
logoFile="assets/glass/icon.png"

[[mixins]]
config="glass.mixins.json"

[[dependencies.glass]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.glass]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[features.glass]
javaVersion="[21,)"
